const languages = [
  {
    no: "0",
    name: "Auto",
    native: "Détection",
    code: "auto",
  },
  {
    no: "1",
    name: "Afrikaans",
    native: "Afrikaans",
    code: "af",
  },
  {
    no: "2",
    name: "Albanian",
    native: "Albanais",
    code: "sq",
  },
  {
    no: "3",
    name: "Arabic",
    native: "Arabe",
    code: "ar",
  },
  {
    no: "4",
    name: "Armenian",
    native: "Arménien",
    code: "hy",
  },
  {
    no: "5",
    name: "Azerbaijani",
    native: "Azéri",
    code: "az",
  },
  {
    no: "6",
    name: "Basque",
    native: "Basque",
    code: "eu",
  },
  {
    no: "7",
    name: "Belarusian",
    native: "Biélorusse",
    code: "be",
  },
  {
    no: "8",
    name: "Bulgarian",
    native: "Bulgare",
    code: "bg",
  },
  {
    no: "9",
    name: "Catalan",
    native: "Catalan",
    code: "ca",
  },
  {
    no: "10",
    name: "Chinese (Simplified)",
    native: "Chinois (Simplifié)",
    code: "zh-CN",
  },
  {
    no: "11",
    name: "Chinese (Traditional)",
    native: "Chinois (Traditionnel)",
    code: "zh-TW",
  },
  {
    no: "12",
    name: "Croatian",
    native: "Croate",
    code: "hr",
  },
  {
    no: "13",
    name: "Czech",
    native: "Tchèque",
    code: "cs",
  },
  {
    no: "14",
    name: "Danish",
    native: "Danois",
    code: "da",
  },
  {
    no: "15",
    name: "Dutch",
    native: "Néerlandais",
    code: "nl",
  },
  {
    no: "16",
    name: "English",
    native: "Anglais",
    code: "en",
  },
  {
    no: "17",
    name: "Estonian",
    native: "Estonien",
    code: "et",
  },
  {
    no: "18",
    name: "Filipino",
    native: "Filipino",
    code: "tl",
  },
  {
    no: "19",
    name: "Finnish",
    native: "Finnois",
    code: "fi",
  },
  {
    no: "20",
    name: "French",
    native: "Français",
    code: "fr",
  },
  {
    no: "21",
    name: "Galician",
    native: "Galicien",
    code: "gl",
  },
  {
    no: "22",
    name: "Georgian",
    native: "Géorgien",
    code: "ka",
  },
  {
    no: "23",
    name: "German",
    native: "Allemand",
    code: "de",
  },
  {
    no: "24",
    name: "Greek",
    native: "Grec",
    code: "el",
  },
  {
    no: "25",
    name: "Haitian Creole",
    native: "Créole haïtien",
    code: "ht",
  },
  {
    no: "26",
    name: "Hebrew",
    native: "Hébreu",
    code: "iw",
  },
  {
    no: "27",
    name: "Hindi",
    native: "Hindi",
    code: "hi",
  },
  {
    no: "28",
    name: "Hungarian",
    native: "Hongrois",
    code: "hu",
  },
  {
    no: "29",
    name: "Icelandic",
    native: "Islandais",
    code: "is",
  },
  {
    no: "30",
    name: "Indonesian",
    native: "Indonésien",
    code: "id",
  },
  {
    no: "31",
    name: "Irish",
    native: "Irlandais",
    code: "ga",
  },
  {
    no: "32",
    name: "Italian",
    native: "Italien",
    code: "it",
  },
  {
    no: "33",
    name: "Japanese",
    native: "Japonais",
    code: "ja",
  },
  {
    no: "34",
    name: "Korean",
    native: "Coréen",
    code: "ko",
  },
  {
    no: "35",
    name: "Latvian",
    native: "Letton",
    code: "lv",
  },
  {
    no: "36",
    name: "Lithuanian",
    native: "Lituanien",
    code: "lt",
  },
  {
    no: "37",
    name: "Macedonian",
    native: "Macédonien",
    code: "mk",
  },
  {
    no: "38",
    name: "Malay",
    native: "Malais",
    code: "ms",
  },
  {
    no: "39",
    name: "Maltese",
    native: "Maltais",
    code: "mt",
  },
  {
    no: "40",
    name: "Norwegian",
    native: "Norvégien",
    code: "no",
  },
  {
    no: "41",
    name: "Persian",
    native: "Persan",
    code: "fa",
  },
  {
    no: "42",
    name: "Polish",
    native: "Polonais",
    code: "pl",
  },
  {
    no: "43",
    name: "Portuguese",
    native: "Portugais",
    code: "pt",
  },
  {
    no: "44",
    name: "Romanian",
    native: "Roumain",
    code: "ro",
  },
  {
    no: "45",
    name: "Russian",
    native: "Russe",
    code: "ru",
  },
  {
    no: "46",
    name: "Serbian",
    native: "Serbe",
    code: "sr",
  },
  {
    no: "47",
    name: "Slovak",
    native: "Slovaque",
    code: "sk",
  },
  {
    no: "48",
    name: "Slovenian",
    native: "Slovène",
    code: "sl",
  },
  {
    no: "49",
    name: "Spanish",
    native: "Espagnol",
    code: "es",
  },
  {
    no: "50",
    name: "Swahili",
    native: "Swahili",
    code: "sw",
  },
  {
    no: "51",
    name: "Swedish",
    native: "Suédois",
    code: "sv",
  },
  {
    no: "52",
    name: "Thai",
    native: "Thaïlandais",
    code: "th",
  },
  {
    no: "53",
    name: "Turkish",
    native: "Turc",
    code: "tr",
  },
  {
    no: "54",
    name: "Ukrainian",
    native: "Ukrainien",
    code: "uk",
  },
  {
    no: "55",
    name: "Urdu",
    native: "Ourdou",
    code: "ur",
  },
  {
    no: "56",
    name: "Vietnamese",
    native: "Vietnamien",
    code: "vi",
  },
  {
    no: "57",
    name: "Welsh",
    native: "Gallois",
    code: "cy",
  },
  {
    no: "58",
    name: "Yiddish",
    native: "Yiddish",
    code: "yi",
  },
];
